all_para_settings = {
    "camera": {
        # "brief": [
        #     {"str": "— 摄像参数 —", "name": "", "type": "label"},
        #     {"str": "根目录关键字", "name": "patient_keyword", "type": "str"},
        #     {"str": "拍摄时间节点", "name": "output_time", "type": "int"},
        #     {"str": "末目录关键字", "name": "time_keyword", "type": "str"},
        # ],
        "detail": [
            {"str": "— 多样本拍摄 —", "name": "", "type": "label"},
            {"str": "样本数量", "name": "sample_num", "type": "int"},
            {"str": "帧率 (fps)", "name": "vimbaX_AcquisitionFrameRate", "type": "float"},
            # {"str": "", "name": "range=(1.0369e-05, 289.04776)", "type": "label"},
            {"str": "单次拍摄时长 (s) ", "name": "video_period", "type": "int"},
            {"str": "拍摄时间间隔 (min)", "name": "video_interval", "type": "int"},
            {"str": "拍摄截止时间 (min)", "name": "video_end_time", "type": "int"},

            {"str": "— 相机参数 —", "name": "", "type": "label"},
            {"str": "曝光时间", "name": "vimbaX_ExposureTime", "type": "float"},
            # {"str": "", "name": "range=(176.687, 10000009.253)", "type": "label"},
            {"str": "增益", "name": "vimbaX_Gain", "type": "float"},
            # {"str": "", "name": "range=(0.0, 24.0000)", "type": "label"},
            {"str": "像素深度", "name": "vimbaX_SensorBitDepth", "type": {
                "Adaptive":0,
                "Bpp8":1,
                "Bpp10":2,
                "Bpp12":3,
            }},

            {"str": "— 对比度处理 —", "name": "", "type": "label"},
            {"str": "最高亮度", "name": "contrast_max", "type": "float"},
            {"str": "最低亮度", "name": "contrast_min", "type": "float"},
        ],
    },
    "load":{
        # "brief": [],
        "detail":[
            # {"str": "— 文件与路径 —", "name": "", "type": "label"},
            # {"str": "根目录关键字", "name": "patient_keyword", "type": "str"},
            # {"str": "拍摄组名", "name": "output_group", "type": "str"},
            # {"str": "拍摄时间节点", "name": "output_time", "type": "int"},
            # {"str": "末目录关键字", "name": "time_keyword", "type": "str"},
            # {"str": "数据类型", "name": "extensions", "type": "str"},
        ],
    },
    "preprocess": {
        # "brief": [
        #     {"str": "— 噪声过滤 —", "name": "", "type": "label"},
        #     {"str": "视频间隔帧数", "name": "frame_step", "type": "int"},
        #     {"str": "抖动怀疑阈值", "name": "sus_threshold", "type": "float"},
        #     {"str": "局部最小值步长", "name": "local_min_len", "type": "int"},
        #     {"str": "中值滤波半径", "name": "subtract_rolling", "type": "float"},
        # ],
        "detail": [
            {"str": "— 视频除抖 —", "name": "", "type": "label"},
            {"str": "视频间隔帧数", "name": "frame_step", "type": "int"},
            {"str": "抖动二值化阈值", "name": "shake_binary_threshold", "type": "float"},
            {"str": "抖动平滑步长", "name": "min_filter_len", "type": "int"},
            {"str": "迭代次数限制", "name": "iteration_limit", "type": "int"},
            {"str": "迭代步长", "name": "iteration_step", "type": "float"},
            {"str": "抖动怀疑阈值", "name": "sus_threshold", "type": "float"},
            {"str": "抖动判定阈值", "name": "shake_threshold", "type": "float"},

            {"str": "— 噪声过滤 —", "name": "", "type": "label"},
            {"str": "局部最小值步长", "name": "local_min_len", "type": "int"},
            {"str": "中值滤波半径", "name": "subtract_rolling", "type": "float"},
            {"str": "1 类离群值半径", "name": "outliers_radius_1", "type": "int"},
            {"str": "1 类离群值阈值", "name": "outliers_threshold_1", "type": "int"},
            {"str": "2 类离群值半径", "name": "outliers_radius_2", "type": "int"},
            {"str": "2 类离群值阈值", "name": "outliers_threshold_2", "type": "int"},

            {"str": "— 形态学微调 —", "name": "", "type": "label"},
            {"str": "黑洞二值化阈值", "name": "zero_part_threshold", "type": "float"},
            {"str": "闭运算迭代次数", "name": "close_iteration", "type": "int"},
            {"str": "闭运算半径", "name": "close_count", "type": "int"},
            {"str": "膨胀迭代次数", "name": "dilate_iteration", "type": "int"},
            {"str": "膨胀半径", "name": "dilate_count", "type": "int"},
            {"str": "亮度提高幅度", "name": "enhance_brightness", "type": "float"},
        ],
    },
    "trackmate": {
        # "brief": [
        #     {"str": "— 检测追踪 —", "name": "", "type": "label"},
        #     {"str": "开启杂志过滤", "name": "huge_impurity_filter", "type": "bool"},
        #     {"str": "过滤时间限定", "name": "huge_impurity_time", "type": "int"},
        #     {"str": "长菌判定阈值", "name": "LD_intensity_threshold", "type": "float"},
        #     {"str": "长菌面积筛选", "name": "LDF_area", "type": "float"},
        #     {"str": "长菌追踪最大距离", "name": "LT_linking_max_distance", "type": "float"},
        #     {"str": "长菌轨迹约束比", "name": "LTF_confinement_ratio", "type": "float"},
        #     {"str": "短菌检测半径", "name": "ND_radius", "type": "float"},
        #     {"str": "短菌检测阈值", "name": "ND_threshold", "type": "float"},
        #     {"str": "短菌信噪比筛选", "name": "NDF_snr", "type": "float"},
        #     {"str": "短菌追踪最大距离", "name": "NT_linking_max_distance", "type": "float"},
        #     {"str": "短菌轨迹约束比", "name": "NTF_confinement_ratio", "type": "float"},
        # ],
        "detail": [
            {"str": "— 大体积杂质过滤 —", "name": "", "type": "label"},
            {"str": "开启杂志过滤", "name": "huge_impurity_filter", "type": "bool"},
            {"str": "过滤时间限定", "name": "huge_impurity_time", "type": "int"},
            {"str": "过滤参数补正", "name": "huge_impurity_intensity_add", "type": "float"},

            {"str": "— 长细菌检测 —", "name": "", "type": "label"},
            {"str": "检测通道", "name": "LD_target_channel", "type": "int"},
            {"str": "简化等高线", "name": "LD_simplify_contours", "type": "bool"},
            {"str": "判定阈值", "name": "LD_intensity_threshold", "type": "float"},

            {"str": "— 长细菌检测筛选 —", "name": "", "type": "label"},
            {"str": "检测面积筛选", "name": "LDF_area", "type": "float"},

            {"str": "— 长细菌追踪 —", "name": "", "type": "label"},
            {"str": "中断允许间隔", "name": "LT_max_frame_gap", "type": "int"},
            {"str": "中断允许距离", "name": "LT_gap_closing_max_distance", "type": "float"},
            {"str": "追踪最大距离", "name": "LT_linking_max_distance", "type": "float"},

            {"str": "— 长细菌追踪筛选 —", "name": "", "type": "label"},
            {"str": "轨迹位移筛选", "name": "LTF_track_displacement", "type": "float"},
            {"str": "轨迹时长筛选", "name": "LTF_number_spots", "type": "float"},
            {"str": "轨迹约束比筛选", "name": "LTF_confinement_ratio", "type": "float"},
            {"str": "轨迹中断筛选", "name": "LTF_number_gaps", "type": "float"},

            {"str": "— 长细菌去除 —", "name": "", "type": "label"},
            {"str": "闭运算迭代次数", "name": "WL_close_iteration", "type": "int"},
            {"str": "闭运算半径", "name": "WL_close_count", "type": "int"},
            {"str": "膨胀迭代次数", "name": "WL_dilate_iteration", "type": "int"},
            {"str": "膨胀半径", "name": "WL_dilate_count", "type": "int"},

            {"str": "— 短细菌检测 —", "name": "", "type": "label"},
            {"str": "开启亚像素定位", "name": "ND_do_subpixel_localization", "type": "bool"},
            {"str": "检测半径", "name": "ND_radius", "type": "float"},
            {"str": "检测通道", "name": "ND_target_channel", "type": "int"},
            {"str": "检测阈值", "name": "ND_threshold", "type": "float"},
            {"str": "开启中值滤波", "name": "ND_do_median_filtering", "type": "bool"},

            {"str": "— 短细菌检测筛选 —", "name": "", "type": "label"},
            {"str": "检测最小值筛选", "name": "NDF_min_intensity", "type": "float"},
            {"str": "检测信噪比筛选", "name": "NDF_snr", "type": "float"},

            {"str": "— 短细菌追踪 —", "name": "", "type": "label"},
            {"str": "中断允许间隔", "name": "NT_max_frame_gap", "type": "int"},
            {"str": "中断允许距离", "name": "NT_gap_closing_max_distance", "type": "float"},
            {"str": "追踪最大距离", "name": "NT_linking_max_distance", "type": "float"},

            {"str": "— 短细菌追踪筛选 —", "name": "", "type": "label"},
            {"str": "轨迹位移筛选", "name": "NTF_track_displacement", "type": "float"},
            {"str": "轨迹时长筛选", "name": "NTF_number_spots", "type": "float"},
            {"str": "轨迹约束比筛选", "name": "NTF_confinement_ratio", "type": "float"},
        ],
    },
    "features": {
        # "brief": [
        #     {"str": "— 特征提取 —", "name": "", "type": "label"},
        #     {"str": "重框选起始帧", "name": "ROI_frame_start", "type": "int"},
        #     {"str": "重框选结束帧", "name": "ROI_frame_stop", "type": "int"},
        # ],
        "detail": [
            {"str": "— 重框选 —", "name": "", "type": "label"},
            {"str": "重框选起始帧", "name": "ROI_frame_start", "type": "int"},
            {"str": "重框选结束帧", "name": "ROI_frame_stop", "type": "int"},
            {"str": "背景判定阈值", "name": "ROI_0_thres", "type": "float"},
            {"str": "1 类梯度判定阈值", "name": "ROI_1_thres", "type": "float"},
            {"str": "2 类梯度判定阈值", "name": "ROI_2_thres", "type": "float"},
            {"str": "最高判定阈值", "name": "ROI_h_thres", "type": "float"},
            {"str": "最低迭代次数", "name": "ROI_at_least", "type": "float"},

            {"str": "— 特征计算 —", "name": "", "type": "label"},
            {"str": "1 类热流平滑步长", "name": "smooth_window_len_1", "type": "int"},
            {"str": "2 类热流平滑步长", "name": "smooth_window_len_2", "type": "int"},
            {"str": "3 类热流平滑步长", "name": "smooth_window_len_3", "type": "int"},
            {"str": "1 类闪烁判定阈值", "name": "shine_tolerance_1", "type": "float"},
            {"str": "2 类闪烁判定阈值", "name": "shine_tolerance_2", "type": "float"},
            {"str": "3 类闪烁判定阈值", "name": "shine_tolerance_3", "type": "float"},
        ],
    },
}
